site_name: ADP API Client Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - ADP API Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md