[project]
name = "adpapi"
version = "1.0.0"
description = "Add your description here"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
authors = [
    {name = "Joey Russoniello", email = "jmrusso@bu.edu"}
]

dependencies = [
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
classifiers = [
    'Programming Language :: Python :: 3.10', 
    'Programming Language :: Python :: 3.11', 
    'Operating System :: OS Independent', 
    'Intended Audience :: Developers', 
    'Topic :: Software Development :: Libraries :: Python Modules'
]

[project.optional-dependencies]

dev = [
'pytest>=7.0.0', 'pytest-cov>=4.0.0', 'black>=22.0.0', 'flake8>=4.0.0'
]

[project.urls]
Homepage = "https://github.com/JoeyRussoniello/Adp-Api-Client"


[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pyyaml>=6.0.3",
]
