[project]
name = "adpapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Joey Russoniello", email = "jmrusso@bu.edu"}
]

dependencies = [
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
classifiers = [
    'Programming Language :: Python :: 3.10', 
    'Programming Language :: Python :: 3.11', 
    'Operating System :: OS Independent', 
    'Intended Audience :: Developers', 
    'Topic :: Software Development :: Libraries :: Python Modules'
]
[project.optional-dependencies]

dev = [
'pytest>=7.0.0', 'pytest-cov>=4.0.0', 'black>=22.0.0', 'flake8>=4.0.0'
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]