name: Docs
on:
  pull_request:
    paths: ['docs/**', 'mkdocs.yml', 'src/**', '.github/workflows/docs.yml']
  push:
    branches: [ main ]    
    paths: ['docs/**', 'mkdocs.yml', 'src/**', '.github/workflows/docs.yml']

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pipx install uv
      - run: uv sync --dev
      - run: uv run mkdocs build --strict

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy